### PR TITLE
add iOS things

### PR DESCRIPTION
**Pull request by auggeeo**
This prob doesn't change anything about this but idc, and just in case i guess idk really.

### CODE REVIEW

**Comment by RoootTheFox** [comment]
i should've maybe made it more clear that this isn't a mod anymore (but an API/library for use in mods)

**Comment by RoootTheFox** [comment]
in other words, i forgot to remove the mod.json and workflows.

**Comment by auggeeo** [comment]
oh lol whoops

**Comment by RoootTheFox** [comment]
nah my fault, ur good lmao

**Pull request closed without merging**
